export enum Paths {
  LOGIN = '/login',
  HOME = '/',
  DESTINY = '/destino',
  HEALTH = '/health',
  ARTICLE = '/article/:id',
  BADGES = '/badges',
  TRIP = '/trip/:destiny',
  TRIP_WITH_TIMER = '/trip/:destiny/:time?',
  TRIP_QUERY = '/trip/',
  FINISHED_TRIP = '/finished-trip',
  MY_TRIPS = '/my-trips',
  PAUSED_TRIP = '/paused-trip',
  PAUSED_TRIP_WITH_TIME = '/paused-trip/:time',
}
